language: python
python: 
 - 2.7
 - 3.3
 - 3.4
install:
 - pip install -U setuptools
 - python setup.py develop
 - pip install -r requirements
 - pip install -U pytest-cov coveralls
script:
    py.test --cov housenumparser --cov-report term-missing tests
after_success:
    coveralls
