language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install -U setuptools
  - python setup.py develop
  - pip install -r requirements-dev.txt
  - pip install -U pytest-cov coveralls
script:
  - flake8
  - py.test --cov housenumparser --cov-report term-missing tests
after_success:
  coveralls
