name: housenumparser backend tests
on:
  pull_request:
    paths:
      - housenumparser/**
      - tests/**
      - .github/workflows/housenum_parser.yml
      - pyproject.toml
      - requirements*.txt

  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install python requirements
        env:
          HATCH_BUILD_NO_HOOKS: true
        working-directory: ./
        run: |
          pip --version
          pip install pip-tools
          pip-sync requirements-dev.txt
          pip install -e .

      - name: Python tests
        run: pytest tests --cov=housenumparser --cov-report=xml --capture=no -vvv

      - name: Code Coverage Report
        if: matrix.python-version == '3.11'
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0.8
          thresholdModified: 0.8
